Calculator fa = new Calculator();
fa.carColor = 'gray';
fa.carName = 'Honda';
fa.switchOn();


fa.drive();
fa.driveAtMaxSpeed();










Calculator calc = new Calculator();
integer sum1 = calc.add(10,15);
system.debug('sum1 is ' +sum1);

integer sum11 = calc.add(10,15, 25);
system.debug('sum11 is ' + sum11);

string sum21 = calc.add('Esra ', 25);
system.debug('sum2 is ' +sum21);

string yakup = calc.firinci();
system.debug (yakup+' aldi evine gidiyormutlu');

calc.firinci2();




