public  class checkDatatypes {
    public void methodBoolean() {
      Boolean checkBoolean = true;
      system.debug('Value of checkBoolean; ' + checkBoolean);
        
    }
    public void MethodInteger(){
        integer varfirst = 1;
        integer varsecond = 2; 
        system.debug('varfirst ' + varfirst);
        system.debug('varsecond ' + varsecond);
    }
    public void Stringmethod(){
        string varName = 'Name';
        string var2Name = 'Fatma';
        system.debug('Value of Name ' +varName +var2Name);
        
    }
}