ListDemo.candidatesList(10);
ListDemo.randomIntegerList();



List<integer> mahmut = new List<integer>();
mahmut.add(10);
mahmut.add(15);
mahmut.add(21);
mahmut.add(15);
integer sumofList = ListDemo.add(mahmut);
system.debug ('sum of list is ' +sumofList);

string c2 = ListDemo.candidatesList(2);
system.debug('c2 ==. ' + c2);
string c5= ListDemo.candidatesList(5);
system.debug('c5 ==> ' + c5);



