system.debug('Merhaba sima');
system.debug('Merhaba sena');

HelloTrReview htr = new HelloTrReview();
htr.switchOn();


string ifade = 'bugun hava guzel';
system.debug(ifade);

string isimsoyisim = 'fatma afsin';
system.debug(isimsoyisim);

integer zipcode = 75050;
system.debug(zipcode);

string firstName = 'fatma';
string lastName = 'afsin'; 
//yorum yaziyorsun buraya//
string fullName = firstName +    lastName ;
system.debug(fullName);

